spring:
  application:
    name: JDBC-to-JPA

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        generate_statistics: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

#logging:
#  level:
#    org:
#      hibernate:
#        stat: DEBUG
#        type: TRACE




